import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from "next/link"

export default function Home() {
  const [productList, setProductList] = useState<TProduct[]>([]);
  const [loading, setLoading] = useState(false);
  
  useEffect(() => {
    setLoading(true);
    fetch('/api/avo')
    .then((response) => response.json())
    .then(({ data, length }) => {
      setProductList(data);
    })
    .finally(() => setLoading(false))
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-3xl text-lime-400 pt-5'>Avocados</h1>
        {!loading ? 
                <ul className='mt-4 flex flex-wrap justify-center gap-4 px-5 min-h-[1100px]'>
                {productList.map(product => (
                  <li key={product.id} className='border border-gray-500 rounded-lg pb-2'>
                    <Link href={`/product/${product.id}`}>
                      <img src={product.image} className='w-[300px] rounded-t-lg' alt={product.name}/>
                      <p className='mt-3 font-medium text-lg leading-5'>{product.name}</p>
                      <div className='text-lime-400'>{product.price}</div>
                    </Link>
                  </li>
                ))}
      
              </ul> : <div className='mt-4 min-h-[1100px]'>Loading...</div>
        }

      </main>
    </div>
  )
}
